

REQUEST_NAME: str = "Hi! May I ask for your name? "
GREETING: str = "\nIt's a pleasure to meet you {username}! \nUnfortunately I don't have a specific name but they call me UniBot so we can stick with it. \nI was designed to help first-year students access important informations about our university. \n \nSooo how may I help? :3 \n"
CHOOSE_TOPIC: str = "Ask a question: "
CATEGORY_NOT_DEFINED: str = "\nOh dear {username}... \nI've got no clue what you're talking about gtfo\n"
END_CONVERSATION: str = "If you wish to end conversation feel write to write '{end_keyword}'"
END_MESSAGE: str = "\nIt was a pleasure talking to you {username}!\n"
IS_STRUGGLING: str = "\nSo you decided to ask me about studying hm? Are you struggling with something? \n\nIf yes: type YES, otherwise type NO\n\nYour answer: "
WANT_TO_SHARE: str = "\nI understand that studying might be difficult sometimes. Would you like to share it with other students? \n\nIf yes: type YES, otherwise type NO\n\nYour answer: "
SUGGESTION_STUDY_GROUP: str = ""
SUGGESTION_STUDENT_ADVISOR: str = ""
SUGGESTION_STUDENT_DESK: str = ""
SUGGESTION_SPORTS_CENTRE: str = ""
SPORT_NOT_AVAILABLE: str = "Unfortunately this sport is not available at our university but maybe you would like to try one of these:"
FINAL_ADNOTAION: str = "If there's anything else I can do for you, feel free to ask!"
YES_NO_INCORRECT_RESPONSE: str = "\n{username}!\nIf you want me to help I need you to answer YES or NO!\n"
HAS_SPECIFIC_SPORT: str = "Do you have specific sport in mind?"
QUESTION_SPECIFIC_SPORT: str = "Which sport do you have in mind?"
EVENTS_OR_ASSOCIATIONS: str = ""
EVENTS_OR_ASSOCIATIONS_ERROR: str = ""
ASSOCIATION_FIT: str = ""